plugins {
    id 'net.fabricmc.fabric-loom' version "${fabric_loom_version}"
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation 'com.google.code.gson:gson:2.13.2'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(project.java_version))
    withSourcesJar()
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = Integer.parseInt(project.java_version)
    options.encoding = 'UTF-8'
}
