org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.1.2
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2
fabric_loom_version=1.16.1
java_version=25
mod_version=3
maven_group=com.epic60869.tastyfish
archives_base_name=tastyfish-mod-26.1.2
