package com.epic60869.tastyfish;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.net.URI;
import java.net.http.*;
import java.time.Duration;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;

public final class FarmingUploader {
    private static final Gson GSON=new Gson(); private static final String MOD_VERSION="1.1.0-26.1.2";
    private static final long AUTH_COOLDOWN_MS=30_000L, BACKOFF_MS=60_000L, MAX_BACKOFF_MS=600_000L;
    private final HttpClient client=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build();
    private volatile String token,tokenUsername,tokenUuid,tokenSessionId; private volatile long authBlockedUntil; private volatile long authBackoffMs=BACKOFF_MS;
    private final AtomicBoolean authing=new AtomicBoolean(false), uploading=new AtomicBoolean(false);
    public void upload(TastyFishConfig c,String username,String uuid,String profile,String sessionId,TastyFishStandalone.Snapshot s){if(!c.enabled||c.endpoint.isBlank()||!s.valid())return;if(username==null||username.isBlank()||uuid==null||uuid.isBlank())return;if(token==null||!username.equalsIgnoreCase(tokenUsername)||!uuid.equalsIgnoreCase(tokenUuid)||!sessionId.equals(tokenSessionId)){authenticate(c,username,uuid,profile,sessionId,s);return;}send(c,username,uuid,profile,sessionId,s,false);}
    private void authenticate(TastyFishConfig c,String u,String id,String profile,String sid,TastyFishStandalone.Snapshot s){long now=System.currentTimeMillis();if(now<authBlockedUntil||!authing.compareAndSet(false,true))return;try{JsonObject b=new JsonObject();b.addProperty("username",u);b.addProperty("uuid",id);b.addProperty("sessionId",sid);b.addProperty("modVersion",MOD_VERSION);HttpRequest r=HttpRequest.newBuilder().uri(URI.create(authEndpoint(c.endpoint))).timeout(Duration.ofSeconds(15)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(GSON.toJson(b))).build();client.sendAsync(r,HttpResponse.BodyHandlers.ofString()).thenAccept(res->{try{if(res.statusCode()>=200&&res.statusCode()<300){JsonObject j=GSON.fromJson(res.body(),JsonObject.class);if(j==null||!j.has("token")){authBlockedUntil=System.currentTimeMillis()+AUTH_COOLDOWN_MS;return;}token=j.get("token").getAsString();tokenUsername=u;tokenUuid=id.toLowerCase();tokenSessionId=sid;authBackoffMs=BACKOFF_MS;authBlockedUntil=System.currentTimeMillis()+AUTH_COOLDOWN_MS;send(c,u,id,profile,sid,s,false);}else if(res.statusCode()==429){long wait=retry(res);authBlockedUntil=System.currentTimeMillis()+wait;authBackoffMs=Math.min(Math.max(authBackoffMs*2,BACKOFF_MS),MAX_BACKOFF_MS);}else authBlockedUntil=System.currentTimeMillis()+AUTH_COOLDOWN_MS;}catch(Exception e){authBlockedUntil=System.currentTimeMillis()+AUTH_COOLDOWN_MS;}finally{authing.set(false);}}).exceptionally(e->{authing.set(false);authBlockedUntil=System.currentTimeMillis()+AUTH_COOLDOWN_MS;return null;});}catch(Exception e){authing.set(false);authBlockedUntil=System.currentTimeMillis()+AUTH_COOLDOWN_MS;}}
    private void send(TastyFishConfig c,String u,String id,String profile,String sid,TastyFishStandalone.Snapshot s,boolean retry){if(!uploading.compareAndSet(false,true))return;JsonObject root=new JsonObject();root.addProperty("username",u);root.addProperty("uuid",id);root.addProperty("profile",profile==null?"":profile);root.addProperty("preset","FARMING");root.addProperty("profit",s.profit());root.addProperty("activeMillis",s.activeMillis());root.addProperty("actions",s.actions());root.addProperty("sessionId",sid);root.add("items",GSON.toJsonTree(s.items()));root.add("pests",GSON.toJsonTree(s.pests()));HttpRequest r=HttpRequest.newBuilder().uri(URI.create(c.endpoint)).timeout(Duration.ofSeconds(15)).header("Content-Type","application/json").header("Authorization","Bearer "+token).POST(HttpRequest.BodyPublishers.ofString(GSON.toJson(root))).build();client.sendAsync(r,HttpResponse.BodyHandlers.ofString()).thenAccept(res->{try{if(res.statusCode()==401&&!retry){token=null;tokenUsername=null;tokenUuid=null;tokenSessionId=null;authenticate(c,u,id,profile,sid,s);}else if(res.statusCode()==429)authBlockedUntil=System.currentTimeMillis()+retry(res);}finally{uploading.set(false);}}).exceptionally(e->{uploading.set(false);return null;});}
    private long retry(HttpResponse<?> r){try{long s=Long.parseLong(r.headers().firstValue("Retry-After").orElse("0"));if(s>0)return Math.min(s*1000L,MAX_BACKOFF_MS);}catch(Exception ignored){}return authBackoffMs;}
    private static String authEndpoint(String e){if(e.endsWith("/update"))return e.substring(0,e.length()-7)+"/auth";return e.endsWith("/")?e+"auth":e+"/auth";}
    public static String newSessionId(){return UUID.randomUUID().toString();}
}
